// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMicrosoftAccount() {
  return window['go']['main']['App']['AddMicrosoftAccount']();
}

export function AddOfflineAccount(arg1) {
  return window['go']['main']['App']['AddOfflineAccount'](arg1);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CancelMicrosoftLogin() {
  return window['go']['main']['App']['CancelMicrosoftLogin']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CleanCache() {
  return window['go']['main']['App']['CleanCache']();
}

export function ClientVersions(arg1) {
  return window['go']['main']['App']['ClientVersions'](arg1);
}

export function Clients() {
  return window['go']['main']['App']['Clients']();
}

export function CopyScreenshotToClipboard(arg1, arg2) {
  return window['go']['main']['App']['CopyScreenshotToClipboard'](arg1, arg2);
}

export function CreateInstance(arg1) {
  return window['go']['main']['App']['CreateInstance'](arg1);
}

export function CurseForgeCategories(arg1) {
  return window['go']['main']['App']['CurseForgeCategories'](arg1);
}

export function CurseForgeFiles(arg1) {
  return window['go']['main']['App']['CurseForgeFiles'](arg1);
}

export function CurseForgeSearch(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CurseForgeSearch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteContent'](arg1, arg2, arg3);
}

export function DeleteDawnFolder() {
  return window['go']['main']['App']['DeleteDawnFolder']();
}

export function DeleteFeatherFolder() {
  return window['go']['main']['App']['DeleteFeatherFolder']();
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteLocalSkin(arg1) {
  return window['go']['main']['App']['DeleteLocalSkin'](arg1);
}

export function DeleteLunarFolder() {
  return window['go']['main']['App']['DeleteLunarFolder']();
}

export function DeleteScreenshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1, arg2);
}

export function DeleteWorld(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorld'](arg1, arg2);
}

export function DiskUsage() {
  return window['go']['main']['App']['DiskUsage']();
}

export function DownloadContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadContent'](arg1, arg2, arg3, arg4);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function DuplicateInstance(arg1) {
  return window['go']['main']['App']['DuplicateInstance'](arg1);
}

export function DuplicateWorld(arg1, arg2) {
  return window['go']['main']['App']['DuplicateWorld'](arg1, arg2);
}

export function ExportInstance(arg1) {
  return window['go']['main']['App']['ExportInstance'](arg1);
}

export function ExportWorld(arg1, arg2) {
  return window['go']['main']['App']['ExportWorld'](arg1, arg2);
}

export function FetchVerifiedPlugins() {
  return window['go']['main']['App']['FetchVerifiedPlugins']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetActiveAccount() {
  return window['go']['main']['App']['GetActiveAccount']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDownloadConcurrency() {
  return window['go']['main']['App']['GetDownloadConcurrency']();
}

export function GetEnabledPlugins() {
  return window['go']['main']['App']['GetEnabledPlugins']();
}

export function GetItemIcon(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetItemIcon'](arg1, arg2, arg3);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetOptions(arg1) {
  return window['go']['main']['App']['GetOptions'](arg1);
}

export function GetPanorama(arg1) {
  return window['go']['main']['App']['GetPanorama'](arg1);
}

export function GetPanoramaVersions() {
  return window['go']['main']['App']['GetPanoramaVersions']();
}

export function GetPersistedState() {
  return window['go']['main']['App']['GetPersistedState']();
}

export function GetPluginCommands() {
  return window['go']['main']['App']['GetPluginCommands']();
}

export function GetPluginPermissions() {
  return window['go']['main']['App']['GetPluginPermissions']();
}

export function GetPluginSettings(arg1) {
  return window['go']['main']['App']['GetPluginSettings'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetScreenshot(arg1, arg2) {
  return window['go']['main']['App']['GetScreenshot'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetSystemMemory() {
  return window['go']['main']['App']['GetSystemMemory']();
}

export function GetWorldInfo(arg1, arg2) {
  return window['go']['main']['App']['GetWorldInfo'](arg1, arg2);
}

export function HttpGet(arg1) {
  return window['go']['main']['App']['HttpGet'](arg1);
}

export function ImportWorld(arg1) {
  return window['go']['main']['App']['ImportWorld'](arg1);
}

export function InspectMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['InspectMod'](arg1, arg2, arg3);
}

export function InspectPluginZip(arg1) {
  return window['go']['main']['App']['InspectPluginZip'](arg1);
}

export function InstallModpack(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallModpack'](arg1, arg2, arg3);
}

export function InstallPluginFromURL(arg1) {
  return window['go']['main']['App']['InstallPluginFromURL'](arg1);
}

export function InstallPluginFromZip(arg1) {
  return window['go']['main']['App']['InstallPluginFromZip'](arg1);
}

export function InstanceSize(arg1) {
  return window['go']['main']['App']['InstanceSize'](arg1);
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function LaunchClientInstance(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LaunchClientInstance'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchInstance(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LaunchInstance'](arg1, arg2, arg3, arg4, arg5);
}

export function ListContent(arg1, arg2) {
  return window['go']['main']['App']['ListContent'](arg1, arg2);
}

export function ListLocalSkins() {
  return window['go']['main']['App']['ListLocalSkins']();
}

export function ListPlugins(arg1) {
  return window['go']['main']['App']['ListPlugins'](arg1);
}

export function ListScreenshots(arg1) {
  return window['go']['main']['App']['ListScreenshots'](arg1);
}

export function ListWorlds(arg1) {
  return window['go']['main']['App']['ListWorlds'](arg1);
}

export function LogsTail(arg1) {
  return window['go']['main']['App']['LogsTail'](arg1);
}

export function OpenInstanceFolder(arg1) {
  return window['go']['main']['App']['OpenInstanceFolder'](arg1);
}

export function OpenScreenshotsFolder(arg1) {
  return window['go']['main']['App']['OpenScreenshotsFolder'](arg1);
}

export function OpenWorldFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenWorldFolder'](arg1, arg2);
}

export function PickJavaFile() {
  return window['go']['main']['App']['PickJavaFile']();
}

export function PickPluginFile() {
  return window['go']['main']['App']['PickPluginFile']();
}

export function PluginFetch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginFetch'](arg1, arg2, arg3, arg4);
}

export function PluginSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSend'](arg1, arg2, arg3);
}

export function PollMicrosoftLogin(arg1, arg2) {
  return window['go']['main']['App']['PollMicrosoftLogin'](arg1, arg2);
}

export function PruneOrphanedVersions(arg1) {
  return window['go']['main']['App']['PruneOrphanedVersions'](arg1);
}

export function RemovePlugin(arg1) {
  return window['go']['main']['App']['RemovePlugin'](arg1);
}

export function RenameInstance(arg1, arg2) {
  return window['go']['main']['App']['RenameInstance'](arg1, arg2);
}

export function RenameWorld(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameWorld'](arg1, arg2, arg3);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RunPluginCommand(arg1, arg2) {
  return window['go']['main']['App']['RunPluginCommand'](arg1, arg2);
}

export function SaveOptions(arg1, arg2) {
  return window['go']['main']['App']['SaveOptions'](arg1, arg2);
}

export function SavePluginSettings(arg1, arg2) {
  return window['go']['main']['App']['SavePluginSettings'](arg1, arg2);
}

export function SaveState(arg1, arg2) {
  return window['go']['main']['App']['SaveState'](arg1, arg2);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function SetDownloadConcurrency(arg1) {
  return window['go']['main']['App']['SetDownloadConcurrency'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function StopInstance() {
  return window['go']['main']['App']['StopInstance']();
}

export function TestJavaPath(arg1) {
  return window['go']['main']['App']['TestJavaPath'](arg1);
}

export function ToggleContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleContent'](arg1, arg2, arg3, arg4);
}

export function UploadSkin(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadSkin'](arg1, arg2, arg3);
}
