// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';
import {main} from '../models';
import {updater} from '../models';
import {plugin} from '../models';
import {panorama} from '../models';

export function AddMicrosoftAccount():Promise<launcher.DeviceCode>;

export function AddOfflineAccount(arg1:string):Promise<main.PubAccount>;

export function ApplyUpdate():Promise<void>;

export function CancelInstall():Promise<void>;

export function CancelMicrosoftLogin():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function CleanCache():Promise<launcher.CleanReport>;

export function ClientVersions(arg1:string):Promise<Array<launcher.ClientVersion>>;

export function Clients():Promise<Array<launcher.ClientInfo>>;

export function CopyScreenshotToClipboard(arg1:string,arg2:string):Promise<void>;

export function CreateInstance(arg1:string):Promise<string>;

export function CurseForgeCategories(arg1:number):Promise<string>;

export function CurseForgeFiles(arg1:string):Promise<string>;

export function CurseForgeSearch(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<string>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDawnFolder():Promise<void>;

export function DeleteFeatherFolder():Promise<void>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DeleteLocalSkin(arg1:string):Promise<void>;

export function DeleteLunarFolder():Promise<void>;

export function DeleteScreenshot(arg1:string,arg2:string):Promise<void>;

export function DeleteWorld(arg1:string,arg2:string):Promise<void>;

export function DiskUsage():Promise<Array<launcher.StorageCategory>>;

export function DownloadContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadUpdate():Promise<void>;

export function DuplicateInstance(arg1:string):Promise<string>;

export function DuplicateWorld(arg1:string,arg2:string):Promise<string>;

export function ExportInstance(arg1:string):Promise<string>;

export function ExportWorld(arg1:string,arg2:string):Promise<string>;

export function FetchVerifiedPlugins():Promise<main.VerifiedCatalog>;

export function GetAccounts():Promise<Array<main.PubAccount>>;

export function GetActiveAccount():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDownloadConcurrency():Promise<number>;

export function GetEnabledPlugins():Promise<Array<plugin.InstalledPlugin>>;

export function GetItemIcon(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function GetOptions(arg1:string):Promise<Array<launcher.Option>>;

export function GetPanorama(arg1:string):Promise<any>;

export function GetPanoramaVersions():Promise<Array<panorama.VersionEntry>>;

export function GetPersistedState():Promise<string>;

export function GetPluginCommands():Promise<Record<string, Array<string>>>;

export function GetPluginPermissions():Promise<Array<string>>;

export function GetPluginSettings(arg1:string):Promise<Record<string, any>>;

export function GetProgress():Promise<launcher.Progress>;

export function GetScreenshot(arg1:string,arg2:string):Promise<string>;

export function GetState():Promise<launcher.State>;

export function GetSystemMemory():Promise<number>;

export function GetWorldInfo(arg1:string,arg2:string):Promise<launcher.WorldInfo>;

export function HttpGet(arg1:string):Promise<string>;

export function ImportWorld(arg1:string):Promise<string>;

export function InspectMod(arg1:string,arg2:string,arg3:string):Promise<launcher.ModInfo>;

export function InspectPluginZip(arg1:string):Promise<plugin.Manifest>;

export function InstallModpack(arg1:string,arg2:string,arg3:string):Promise<launcher.ModpackInfo>;

export function InstallPluginFromURL(arg1:string):Promise<plugin.InstalledPlugin>;

export function InstallPluginFromZip(arg1:string):Promise<plugin.InstalledPlugin>;

export function InstanceSize(arg1:string):Promise<number>;

export function IsGameRunning():Promise<boolean>;

export function LaunchClientInstance(arg1:string,arg2:string,arg3:string,arg4:string,arg5:launcher.LaunchOptions):Promise<void>;

export function LaunchInstance(arg1:string,arg2:string,arg3:string,arg4:string,arg5:launcher.LaunchOptions):Promise<void>;

export function ListContent(arg1:string,arg2:string):Promise<Array<launcher.Plugin>>;

export function ListLocalSkins():Promise<Array<launcher.LocalSkin>>;

export function ListPlugins(arg1:string):Promise<Array<launcher.Plugin>>;

export function ListScreenshots(arg1:string):Promise<Array<launcher.Screenshot>>;

export function ListWorlds(arg1:string):Promise<Array<launcher.World>>;

export function LogsTail(arg1:number):Promise<Array<string>>;

export function OpenInstanceFolder(arg1:string):Promise<void>;

export function OpenScreenshotsFolder(arg1:string):Promise<void>;

export function OpenWorldFolder(arg1:string,arg2:string):Promise<void>;

export function PickJavaFile():Promise<string>;

export function PickPluginFile():Promise<string>;

export function PluginFetch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function PluginSend(arg1:string,arg2:string,arg3:any):Promise<void>;

export function PollMicrosoftLogin(arg1:string,arg2:number):Promise<main.PubAccount>;

export function PruneOrphanedVersions(arg1:Array<string>):Promise<Array<launcher.PruneReport>>;

export function RemovePlugin(arg1:string):Promise<void>;

export function RenameInstance(arg1:string,arg2:string):Promise<void>;

export function RenameWorld(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestartApp():Promise<void>;

export function RunPluginCommand(arg1:string,arg2:string):Promise<any>;

export function SaveOptions(arg1:string,arg2:Array<launcher.Option>):Promise<void>;

export function SavePluginSettings(arg1:string,arg2:string):Promise<void>;

export function SaveState(arg1:string,arg2:string):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function SetDownloadConcurrency(arg1:number):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StopInstance():Promise<void>;

export function TestJavaPath(arg1:string):Promise<string>;

export function ToggleContent(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UploadSkin(arg1:string,arg2:string,arg3:string):Promise<void>;
